shell.run("rm /Applications/sparkDevUtils")
shell.run("rm /Applications/CONSULT")
shell.run("rm /Applications/sparkFiles")
shell.run("rm /Applications/sparkMediaCreator")
shell.run("rm /Manifests/sparkFiles.lua")
shell.run("rm /Manifests/CONSULT.lua")
shell.run("rm /Manifests/sparkMediaCreator.lua")

shell.run("mkdir /Applications/sparkDevUtils")
shell.run("wget https://raw.githubusercontent.com/StikyPiston/sparkDevUtils/HEAD/packer.lua /Applications/sparkDevUtils/packer.lua")
shell.run("wget https://raw.githubusercontent.com/StikyPiston/sparkDevUtils/HEAD/pack.lua   /Applications/sparkDevUtils/pack.lua")
shell.run("wget run https://codeberg.org/StikyPiston/sparkPorts/raw/branch/main/CONSULT/install.lua")
shell.run("wget run https://codeberg.org/StikyPiston/sparkFiles/raw/branch/main/install.lua")
shell.run("wget run https://codeberg.org/StikyPiston/sparkMediaCreator/raw/branch/main/install.lua")
