shell.run("rm /Applications/sparkDevUtils")
shell.run("rm /Applications/consult")
shell.run("rm /Applications/sparkFiles")
shell.run("rm /Applications/sparkmediacreator")
shell.run("rm /Manifests/sparkFiles.lua")
shell.run("rm /Manifests/CONSULT.lua")
shell.run("rm /Manifests/sparkMediaCreator.lua")
